credentials:
  usernames:
    pramirez:
      email: pramirez76@gmail.com
      name: Pablo
      password: '$2b$12$Lu0FMt49yx7K0cACLOnu0uMuAp2LGO9fBePPhfOF0yz4NjRDH.2UG'
    pablo_ucm:
      email: pablo@bsci.finance
      name: Pablo BSCI
      password: '$2b$12$E3VZGKS5Cl2yjN0W.PQBnuHAGB9CYMetpM1j58KpWeOSgnOf4fi0O'
    usuario1:
      email: bsci@bsci.finance
      name: BSCI
      password: '$2b$12$aee3XEimA3gLMvUTYyh3sO693HGBAt9RvsL/5FWktAqwqfEGKjsye'
cookie:
  expiry_days: 30
  key: 'abcdef' # Must be string
  name: bsci_news
preauthorized:
  emails:

